name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 安装 pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check Linting
        run: pnpm run lint

      # - name: Check Format
      #   run: pnpm run format
      #   continue-on-error: true  # 允许格式问题不导致工作流失败

      - name: Build the project
        run: pnpm run build

      # 设置 SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HUA }}

      # 上传构建结果到指定路径
      - name: Deploy to Server
        run: |
          scp -r .output/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/opt/blog_web/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HUA }}

      - name: Verify uploaded files on the server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'ls -l /opt/blog_web/'

      # 重启 PM2
      - name: Restart PM2 application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'pm2 restart blog_web'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HUA }}
